package com.woniuxy.pojo.example;

import java.util.ArrayList;
import java.util.List;

public class AroomExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aroom
     *
     * @mbggenerated Thu Mar 26 16:26:36 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aroom
     *
     * @mbggenerated Thu Mar 26 16:26:36 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table aroom
     *
     * @mbggenerated Thu Mar 26 16:26:36 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aroom
     *
     * @mbggenerated Thu Mar 26 16:26:36 CST 2020
     */
    public AroomExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aroom
     *
     * @mbggenerated Thu Mar 26 16:26:36 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aroom
     *
     * @mbggenerated Thu Mar 26 16:26:36 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aroom
     *
     * @mbggenerated Thu Mar 26 16:26:36 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aroom
     *
     * @mbggenerated Thu Mar 26 16:26:36 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aroom
     *
     * @mbggenerated Thu Mar 26 16:26:36 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aroom
     *
     * @mbggenerated Thu Mar 26 16:26:36 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aroom
     *
     * @mbggenerated Thu Mar 26 16:26:36 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aroom
     *
     * @mbggenerated Thu Mar 26 16:26:36 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aroom
     *
     * @mbggenerated Thu Mar 26 16:26:36 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aroom
     *
     * @mbggenerated Thu Mar 26 16:26:36 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table aroom
     *
     * @mbggenerated Thu Mar 26 16:26:36 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAroomIdIsNull() {
            addCriterion("aroom_id is null");
            return (Criteria) this;
        }

        public Criteria andAroomIdIsNotNull() {
            addCriterion("aroom_id is not null");
            return (Criteria) this;
        }

        public Criteria andAroomIdEqualTo(Integer value) {
            addCriterion("aroom_id =", value, "aroomId");
            return (Criteria) this;
        }

        public Criteria andAroomIdNotEqualTo(Integer value) {
            addCriterion("aroom_id <>", value, "aroomId");
            return (Criteria) this;
        }

        public Criteria andAroomIdGreaterThan(Integer value) {
            addCriterion("aroom_id >", value, "aroomId");
            return (Criteria) this;
        }

        public Criteria andAroomIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("aroom_id >=", value, "aroomId");
            return (Criteria) this;
        }

        public Criteria andAroomIdLessThan(Integer value) {
            addCriterion("aroom_id <", value, "aroomId");
            return (Criteria) this;
        }

        public Criteria andAroomIdLessThanOrEqualTo(Integer value) {
            addCriterion("aroom_id <=", value, "aroomId");
            return (Criteria) this;
        }

        public Criteria andAroomIdIn(List<Integer> values) {
            addCriterion("aroom_id in", values, "aroomId");
            return (Criteria) this;
        }

        public Criteria andAroomIdNotIn(List<Integer> values) {
            addCriterion("aroom_id not in", values, "aroomId");
            return (Criteria) this;
        }

        public Criteria andAroomIdBetween(Integer value1, Integer value2) {
            addCriterion("aroom_id between", value1, value2, "aroomId");
            return (Criteria) this;
        }

        public Criteria andAroomIdNotBetween(Integer value1, Integer value2) {
            addCriterion("aroom_id not between", value1, value2, "aroomId");
            return (Criteria) this;
        }

        public Criteria andAroomNameIsNull() {
            addCriterion("aroom_name is null");
            return (Criteria) this;
        }

        public Criteria andAroomNameIsNotNull() {
            addCriterion("aroom_name is not null");
            return (Criteria) this;
        }

        public Criteria andAroomNameEqualTo(String value) {
            addCriterion("aroom_name =", value, "aroomName");
            return (Criteria) this;
        }

        public Criteria andAroomNameNotEqualTo(String value) {
            addCriterion("aroom_name <>", value, "aroomName");
            return (Criteria) this;
        }

        public Criteria andAroomNameGreaterThan(String value) {
            addCriterion("aroom_name >", value, "aroomName");
            return (Criteria) this;
        }

        public Criteria andAroomNameGreaterThanOrEqualTo(String value) {
            addCriterion("aroom_name >=", value, "aroomName");
            return (Criteria) this;
        }

        public Criteria andAroomNameLessThan(String value) {
            addCriterion("aroom_name <", value, "aroomName");
            return (Criteria) this;
        }

        public Criteria andAroomNameLessThanOrEqualTo(String value) {
            addCriterion("aroom_name <=", value, "aroomName");
            return (Criteria) this;
        }

        public Criteria andAroomNameLike(String value) {
            addCriterion("aroom_name like", value, "aroomName");
            return (Criteria) this;
        }

        public Criteria andAroomNameNotLike(String value) {
            addCriterion("aroom_name not like", value, "aroomName");
            return (Criteria) this;
        }

        public Criteria andAroomNameIn(List<String> values) {
            addCriterion("aroom_name in", values, "aroomName");
            return (Criteria) this;
        }

        public Criteria andAroomNameNotIn(List<String> values) {
            addCriterion("aroom_name not in", values, "aroomName");
            return (Criteria) this;
        }

        public Criteria andAroomNameBetween(String value1, String value2) {
            addCriterion("aroom_name between", value1, value2, "aroomName");
            return (Criteria) this;
        }

        public Criteria andAroomNameNotBetween(String value1, String value2) {
            addCriterion("aroom_name not between", value1, value2, "aroomName");
            return (Criteria) this;
        }

        public Criteria andAroomCodeIsNull() {
            addCriterion("aroom_code is null");
            return (Criteria) this;
        }

        public Criteria andAroomCodeIsNotNull() {
            addCriterion("aroom_code is not null");
            return (Criteria) this;
        }

        public Criteria andAroomCodeEqualTo(String value) {
            addCriterion("aroom_code =", value, "aroomCode");
            return (Criteria) this;
        }

        public Criteria andAroomCodeNotEqualTo(String value) {
            addCriterion("aroom_code <>", value, "aroomCode");
            return (Criteria) this;
        }

        public Criteria andAroomCodeGreaterThan(String value) {
            addCriterion("aroom_code >", value, "aroomCode");
            return (Criteria) this;
        }

        public Criteria andAroomCodeGreaterThanOrEqualTo(String value) {
            addCriterion("aroom_code >=", value, "aroomCode");
            return (Criteria) this;
        }

        public Criteria andAroomCodeLessThan(String value) {
            addCriterion("aroom_code <", value, "aroomCode");
            return (Criteria) this;
        }

        public Criteria andAroomCodeLessThanOrEqualTo(String value) {
            addCriterion("aroom_code <=", value, "aroomCode");
            return (Criteria) this;
        }

        public Criteria andAroomCodeLike(String value) {
            addCriterion("aroom_code like", value, "aroomCode");
            return (Criteria) this;
        }

        public Criteria andAroomCodeNotLike(String value) {
            addCriterion("aroom_code not like", value, "aroomCode");
            return (Criteria) this;
        }

        public Criteria andAroomCodeIn(List<String> values) {
            addCriterion("aroom_code in", values, "aroomCode");
            return (Criteria) this;
        }

        public Criteria andAroomCodeNotIn(List<String> values) {
            addCriterion("aroom_code not in", values, "aroomCode");
            return (Criteria) this;
        }

        public Criteria andAroomCodeBetween(String value1, String value2) {
            addCriterion("aroom_code between", value1, value2, "aroomCode");
            return (Criteria) this;
        }

        public Criteria andAroomCodeNotBetween(String value1, String value2) {
            addCriterion("aroom_code not between", value1, value2, "aroomCode");
            return (Criteria) this;
        }

        public Criteria andAroomAddrIsNull() {
            addCriterion("aroom_addr is null");
            return (Criteria) this;
        }

        public Criteria andAroomAddrIsNotNull() {
            addCriterion("aroom_addr is not null");
            return (Criteria) this;
        }

        public Criteria andAroomAddrEqualTo(String value) {
            addCriterion("aroom_addr =", value, "aroomAddr");
            return (Criteria) this;
        }

        public Criteria andAroomAddrNotEqualTo(String value) {
            addCriterion("aroom_addr <>", value, "aroomAddr");
            return (Criteria) this;
        }

        public Criteria andAroomAddrGreaterThan(String value) {
            addCriterion("aroom_addr >", value, "aroomAddr");
            return (Criteria) this;
        }

        public Criteria andAroomAddrGreaterThanOrEqualTo(String value) {
            addCriterion("aroom_addr >=", value, "aroomAddr");
            return (Criteria) this;
        }

        public Criteria andAroomAddrLessThan(String value) {
            addCriterion("aroom_addr <", value, "aroomAddr");
            return (Criteria) this;
        }

        public Criteria andAroomAddrLessThanOrEqualTo(String value) {
            addCriterion("aroom_addr <=", value, "aroomAddr");
            return (Criteria) this;
        }

        public Criteria andAroomAddrLike(String value) {
            addCriterion("aroom_addr like", value, "aroomAddr");
            return (Criteria) this;
        }

        public Criteria andAroomAddrNotLike(String value) {
            addCriterion("aroom_addr not like", value, "aroomAddr");
            return (Criteria) this;
        }

        public Criteria andAroomAddrIn(List<String> values) {
            addCriterion("aroom_addr in", values, "aroomAddr");
            return (Criteria) this;
        }

        public Criteria andAroomAddrNotIn(List<String> values) {
            addCriterion("aroom_addr not in", values, "aroomAddr");
            return (Criteria) this;
        }

        public Criteria andAroomAddrBetween(String value1, String value2) {
            addCriterion("aroom_addr between", value1, value2, "aroomAddr");
            return (Criteria) this;
        }

        public Criteria andAroomAddrNotBetween(String value1, String value2) {
            addCriterion("aroom_addr not between", value1, value2, "aroomAddr");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table aroom
     *
     * @mbggenerated do_not_delete_during_merge Thu Mar 26 16:26:36 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table aroom
     *
     * @mbggenerated Thu Mar 26 16:26:36 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}