package com.woniuxy.dao;


import com.woniuxy.pojo.Aroom;
import com.woniuxy.pojo.PageBean;
import com.woniuxy.pojo.example.AroomExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AroomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aroom
     *
     * @mbggenerated Thu Mar 26 16:26:36 CST 2020
     */
    int countByExample(AroomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aroom
     *
     * @mbggenerated Thu Mar 26 16:26:36 CST 2020
     */
    int deleteByExample(AroomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aroom
     *
     * @mbggenerated Thu Mar 26 16:26:36 CST 2020
     */
    int deleteByPrimaryKey(Integer aroomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aroom
     *
     * @mbggenerated Thu Mar 26 16:26:36 CST 2020
     */
    int insert(Aroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aroom
     *
     * @mbggenerated Thu Mar 26 16:26:36 CST 2020
     */
    int insertSelective(Aroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aroom
     *
     * @mbggenerated Thu Mar 26 16:26:36 CST 2020
     */
    List<Aroom> selectByExample(AroomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aroom
     *
     * @mbggenerated Thu Mar 26 16:26:36 CST 2020
     */
    Aroom selectByPrimaryKey(Integer aroomId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aroom
     *
     * @mbggenerated Thu Mar 26 16:26:36 CST 2020
     */
    int updateByExampleSelective(@Param("record") Aroom record, @Param("example") AroomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aroom
     *
     * @mbggenerated Thu Mar 26 16:26:36 CST 2020
     */
    int updateByExample(@Param("record") Aroom record, @Param("example") AroomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aroom
     *
     * @mbggenerated Thu Mar 26 16:26:36 CST 2020
     */
    int updateByPrimaryKeySelective(Aroom record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aroom
     *
     * @mbggenerated Thu Mar 26 16:26:36 CST 2020
     */
    int updateByPrimaryKey(Aroom record);

	/**
	 * @param pageBean
	 * @return
	 */
	List<Aroom> selectByPage(PageBean<Aroom> pageBean);

	/**
	 * @param pageBean
	 * @return
	 */
	int countAll(PageBean<Aroom> pageBean);

	/**
	 * @return
	 */
}